// <auto-generated />
namespace Facebuild.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class UndoAttemptUno : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(UndoAttemptUno));
        
        string IMigrationMetadata.Id
        {
            get { return "202204140918074_UndoAttemptUno"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
